export const MaterialList = [
  {
    id:1,
    materialVal:"metal",
    materialLabel:"METAL",
  },
  {
    id:2,
    materialVal:"mount",
    materialLabel:"MOUNT",
  },
  {
    id:3,
    materialVal:"diamond",
    materialLabel:"DIAMOND",
  },
  {
    id:4,
    materialVal:"colorstone",
    materialLabel:"COLORSTONE",
  },
  {
    id:5,
    materialVal:"finding",
    materialLabel:"FINDING",
  },
  {
    id:6,
    materialVal:"alloy",
    materialLabel:"ALLOY",
  },
  {
    id:7,
    materialVal:"misc",
    materialLabel:"MISC",
  },
]


export const brandMainData = [
    { sr: 1, code: "Cartier", name: "Cartier", description: "", displayOrder: 0 },
    { sr: 2, code: "H&T Jewellaers", name: "H&T Jewellaers", description: "", displayOrder: 1 },
    { sr: 3, code: "BULK", name: "BULK", description: "", displayOrder: 1 },
    { sr: 4, code: "a", name: "a", description: "", displayOrder: 10 },
    { sr: 5, code: "Ammunics", name: "Ammunics", description: "", displayOrder: 10 },
    { sr: 6, code: "A JEWEL", name: "A JEWEL", description: "", displayOrder: 20 },
    { sr: 7, code: "abc", name: "abc", description: "", displayOrder: 30 },
    { sr: 8, code: "abcd", name: "abcd", description: "", displayOrder: 40 },
    { sr: 9, code: "ABJ", name: "Abhushan", description: "AB Jewellers", displayOrder: 50 },
    { sr: 10, code: "Abushan", name: "Abushan", description: "", displayOrder: 60 },
    { sr: 11, code: "ADE", name: "ADE", description: "", displayOrder: 70 },
    { sr: 12, code: "AHI", name: "AHI", description: "", displayOrder: 80 },
    { sr: 13, code: "AK", name: "AK", description: "", displayOrder: 90 },
    { sr: 14, code: "Alankar", name: "Alankar", description: "", displayOrder: 100 },
    { sr: 15, code: "AJ", name: "Amazon Jewellry", description: "For E-commerce", displayOrder: 110 },
    { sr: 16, code: "Amrut Jewellars", name: "Amrut Jewellars", description: "", displayOrder: 120 },
    { sr: 17, code: "Amrut Jewellers", name: "Amrut Jewellers", description: "", displayOrder: 130 },
    { sr: 18, code: "Ankit Jewelers", name: "Ankit Jewelers", description: "", displayOrder: 140 },
    { sr: 19, code: "Anku", name: "anku", description: "", displayOrder: 150 },
    { sr: 20, code: "Apple", name: "Apple", description: "", displayOrder: 160 }
  ];
  export const collectionMainData = [
    { sr: 1, code: "fine jewelry", name: "fine jewelry", description: "", displayOrder: 0 },
    { sr: 2, code: "Necklaces", name: "Necklaces", description: "", displayOrder: 1 },
    { sr: 3, code: "STUDDED", name: "STUDDED", description: "", displayOrder: 1 },
    { sr: 4, code: "BULK", name: "BULK", description: "", displayOrder: 1 },
    { sr: 5, code: "NEW", name: "NEW", description: "", displayOrder: 1 },
    { sr: 6, code: "Aura", name: "Aura", description: "", displayOrder: 1 },
    { sr: 7, code: "Beloved", name: "Beloved", description: "", displayOrder: 1 },
    { sr: 8, code: "12", name: "12", description: "", displayOrder: 10 },
    { sr: 9, code: "coding", name: "coding", description: "", displayOrder: 10 },
    { sr: 10, code: "Women's like", name: "Women's like", description: "testing", displayOrder: 20 },
    { sr: 11, code: "New Star", name: "New Star", description: "", displayOrder: 20 },
    { sr: 12, code: "A DREAMCATHCHERS ROMANCE", name: "A DREAMCATHCHERS ROMANCE", description: "", displayOrder: 20 },
    { sr: 13, code: "a_fashion", name: "a_fashion", description: "", displayOrder: 30 },
    { 
      sr: 14, 
      code: "aaryan", 
      name: "aaryan", 
      description: "kjklkjrgkjhrkjhtjkhtrkhtjkrtjkhkjjktjjkrtkjjtkktktjtjktjktthjkktkjrgkjhrkjhtjkhtrkhtjkrtjkhkjjktjjkrtkjjtkktktjtjktjktthjkktkjrgkjhrkjhtjkhtrkhtjkrtjkhkjjktjjkrtkjjtkktktjtjktjktthjkktkjrgkjhrkjhtjkhtrkhtjkrtjkhkjjktjjkrtkjjtkktktjtjktjktthjkkt", 
      displayOrder: 40 
    },
    { sr: 15, code: "AB", name: "AB", description: "", displayOrder: 50 },
    { sr: 16, code: "A-Collection", name: "A-Collection", description: "A collection", displayOrder: 60 },
    { sr: 17, code: "ADREAMCATHCHERSROMANCE", name: "ADREAMCATHCHERSROMANCE", description: "", displayOrder: 70 },
    { sr: 18, code: "AHILYA", name: "AHILYA", description: "", displayOrder: 80 },
    { sr: 19, code: "AMBROSIAL", name: "AMBROSIAL", description: "", displayOrder: 90 },
    { sr: 20, code: "Amias", name: "Amias", description: "", displayOrder: 100 }
  ];
  export const categorymainData = [
    { sr: 1, code: "antique jewelry", name: "antique jewelry", description: "", displayOrder: 0 },
    { sr: 2, code: "BN", name: "Bridal Necklace", description: "", displayOrder: 1 },
    { sr: 3, code: "KN", name: "Kids necklace", description: "", displayOrder: 1 },
    { sr: 4, code: "PN", name: "Party Necklace", description: "", displayOrder: 1 },
    { sr: 5, code: "BULK", name: "BULK", description: "", displayOrder: 1 },
    { sr: 6, code: "New Category", name: "New Category", description: "", displayOrder: 1 },
    { sr: 7, code: "MOTI", name: "MOTI", description: "", displayOrder: 1 },
    { sr: 8, code: "coding", name: "diamond jwellery", description: "", displayOrder: 1 },
    { sr: 9, code: "KHAKHA OTI", name: "KHAKHA MOTI", description: "", displayOrder: 2 },
    { sr: 10, code: "ss", name: "silverP", description: "", displayOrder: 5 },
    { sr: 11, code: "a&A", name: "a&A", description: "", displayOrder: 10 },
    { sr: 12, code: "A&b", name: "A&b", description: "", displayOrder: 20 },
    { sr: 13, code: "a2", name: "a2", description: "", displayOrder: 30 },
    { sr: 14, code: "Ammu's Ring", name: "Ammu's Ring", description: "", displayOrder: 30 },
    { sr: 15, code: "Ammu\"s Ring", name: "Ammu\"s Ring", description: "", displayOrder: 30 },
    { sr: 16, code: "Girl Necklace", name: "Amazon jewellry", description: "", displayOrder: 40 },
    { sr: 17, code: "Anklet", name: "Anklet", description: "", displayOrder: 50 },
    { sr: 18, code: "A-Ring", name: "A-Ring", description: "", displayOrder: 60 },
    { sr: 19, code: "ARTICLE", name: "ARTICLE", description: "", displayOrder: 70 },
    { sr: 20, code: "ATTACHMENT", name: "ATTACHMENT", description: "", displayOrder: 80 }
  ];
  export const subCategoryMainData = [ 
    { sr: 1, code: "Watch Charms", name: "Watch Charms", description: "", displayOrder: 0, loss: 0.000 },
    { sr: 2, code: "Headtika", name: "Headtika", description: "", displayOrder: 0, loss: 0.000 },
    { sr: 3, code: "Locket", name: "Locket", description: "", displayOrder: 0, loss: 0.000 },
    { sr: 4, code: "Engagement Ring", name: "Engagement Ring", description: "", displayOrder: 1, loss: 0.000 },
    { sr: 5, code: "crystal clear ring", name: "Women Ring", description: "", displayOrder: 1, loss: 0.000 },
    { sr: 6, code: "Bangles", name: "Women Bangles", description: "", displayOrder: 1, loss: 0.000 },
    { sr: 7, code: "Bridal Set", name: "Bridal Set", description: "", displayOrder: 1, loss: 0.000 },
    { sr: 8, code: "MOUNT", name: "MOUNT", description: "", displayOrder: 1, loss: 0.000 },
    { sr: 9, code: "RECONCILE", name: "RECONCILE", description: "", displayOrder: 1, loss: 0.000 },
    { sr: 10, code: "NM SP RING", name: "NM SP RING", description: "", displayOrder: 1, loss: 0.000 },
    { sr: 11, code: "fancyk", name: "fancyk", description: "", displayOrder: 1, loss: 0.000 },
    { sr: 12, code: "Gold chain", name: "Gold chain", description: "", displayOrder: 1, loss: 0.000 },
    { sr: 13, code: "fancynew", name: "fancynew", description: "", displayOrder: 1, loss: 0.000 },
    { sr: 14, code: "V Mangalsutra", name: "V Mangalsutra", description: "", displayOrder: 1, loss: 0.000 },
    { sr: 15, code: "FB", name: "FITTED BANGLES", description: "", displayOrder: 1, loss: 0.000 },
    { sr: 16, code: "Nazaria", name: "Regular2", description: "testing 1", displayOrder: 1, loss: 0.000 },
    { sr: 17, code: "Subcategory 2", name: "Subcategory 2", description: "testing 2", displayOrder: 1, loss: 0.000 },
    { sr: 18, code: "kng", name: "kng", description: "", displayOrder: 1, loss: 0.000 },
    { sr: 19, code: "RNNG", name: "RIING", description: "", displayOrder: 1, loss: 0.000 },
    { sr: 20, code: "Tribal", name: "Tribal", description: "", displayOrder: 1, loss: 0.000 }
  ];
  export const productTypeMainData = [
    { sr: 1, typeCode: "plain jewelry", typeName: "plain jewelry", description: "", displayOrder: 0 },
    { sr: 2, typeCode: "BULK", typeName: "BULK", description: "", displayOrder: 1 },
    { sr: 3, typeCode: "3", typeName: "3", description: "", displayOrder: 3 },
    { sr: 4, typeCode: "5", typeName: "5", description: "", displayOrder: 5 },
    { sr: 5, typeCode: "0 Product Type", typeName: "0 Product Type", description: "", displayOrder: 10 },
    { sr: 6, typeCode: "1", typeName: "1", description: "", displayOrder: 12 },
    { sr: 7, typeCode: "2", typeName: "2", description: "2", displayOrder: 12 },
    { sr: 8, typeCode: "pl", typeName: "priyanklad", description: "", displayOrder: 12 },
    { sr: 9, typeCode: "abcd", typeName: "abcd", description: "", displayOrder: 30 },
    { sr: 10, typeCode: "all", typeName: "all", description: "", displayOrder: 40 },
    { sr: 11, typeCode: "A-ring", typeName: "A-ring", description: "", displayOrder: 50 },
    { sr: 12, typeCode: "AS Jeweller", typeName: "AS Jeweller", description: "", displayOrder: 60 },
    { sr: 13, typeCode: "AT Jeweller", typeName: "AT Jeweller", description: "", displayOrder: 70 },
    { sr: 14, typeCode: "b_goldy", typeName: "b_goldy", description: "", displayOrder: 110 },
    { sr: 15, typeCode: "b_jewellery", typeName: "b_jewellery", description: "jewellery", displayOrder: 120 },
    { sr: 16, typeCode: "baba", typeName: "baba", description: "baba", displayOrder: 130 },
    { sr: 17, typeCode: "b", typeName: "bagu", description: "", displayOrder: 140 },
    { sr: 18, typeCode: "BANGLE Jewellery", typeName: "BANGLE Jewellery", description: "", displayOrder: 150 },
    { sr: 19, typeCode: "Bngl", typeName: "Bangles", description: "", displayOrder: 180 },
    { sr: 20, typeCode: "BRACELET", typeName: "BRACELET", description: "", displayOrder: 190 },
    { sr: 21, typeCode: "brecelet", typeName: "brecelet", description: "", displayOrder: 200 },
    { sr: 22, typeCode: "brecellet", typeName: "brecelet", description: "", displayOrder: 210 },
    { sr: 23, typeCode: "Bridal", typeName: "Bridal", description: "", displayOrder: 220 },
    { sr: 24, typeCode: "chain", typeName: "chain", description: "", displayOrder: 230 },
    { sr: 25, typeCode: "c", typeName: "chandu", description: "", displayOrder: 240 },
    { sr: 26, typeCode: "CZ", typeName: "CZ", description: "", displayOrder: 250 },
    { sr: 27, typeCode: "CZ JEWELLERY", typeName: "CZ JEWELLERY", description: "", displayOrder: 260 },
    { sr: 28, typeCode: "d", typeName: "daya", description: "", displayOrder: 270 },
    { sr: 29, typeCode: "DIAMOIND JEWLLERY", typeName: "DIAMOIND JEWLLERY", description: "", displayOrder: 280 },
    { sr: 30, typeCode: "Diamond", typeName: "Diamond", description: "", displayOrder: 290 },
    { sr: 31, typeCode: "DIAMOND JEW", typeName: "DIAMOND JEW", description: "", displayOrder: 300 },
    { sr: 32, typeCode: "Diamond Jewellery", typeName: "Diamond Jewellery", description: "", displayOrder: 310 },
    { sr: 33, typeCode: "DIAMOND JEWELLWERY", typeName: "DIAMOND JEWELLWERY", description: "", displayOrder: 320 },
    { sr: 34, typeCode: "DIAMOND JWELLERY", typeName: "DIAMOND JWELLERY", description: "", displayOrder: 330 },
    { sr: 35, typeCode: "DM", typeName: "Diamond Necklace", description: "For E-commerce", displayOrder: 350 },
    { sr: 36, typeCode: "DIAMOND RING", typeName: "DIAMOND RING", description: "", displayOrder: 360 },
    { sr: 37, typeCode: "Diamond studded", typeName: "Diamond studded", description: "", displayOrder: 370 },
    { sr: 38, typeCode: "DIAMONDJEWELLERY", typeName: "DIAMONDJEWELLERY", description: "", displayOrder: 380 },
    { sr: 39, typeCode: "dj", typeName: "dj", description: "", displayOrder: 390 },
    { sr: 40, typeCode: "earing", typeName: "earing", description: "", displayOrder: 400 },
    { sr: 41, typeCode: "EARRINGS", typeName: "EARRINGS", description: "", displayOrder: 410 },
    { sr: 42, typeCode: "e", typeName: "ela", description: "", displayOrder: 420 },
    { sr: 43, typeCode: "fancy jewel", typeName: "FANCY JEWEL", description: "", displayOrder: 430 },
    { sr: 44, typeCode: "FLAT DIAMOND JEWELLERY", typeName: "FLAT DIAMOND JEWELLERY", description: "", displayOrder: 440 },
    { sr: 45, typeCode: "flex ring", typeName: "flex ring", description: "", displayOrder: 450 },
    { sr: 46, typeCode: "Gold Jewellery", typeName: "Gold Jewellery", description: "", displayOrder: 460 },
    { sr: 47, typeCode: "Gold Silver Type", typeName: "Gold Silver Type", description: "", displayOrder: 470 },
    { sr: 48, typeCode: "HK jeweller", typeName: "HK jeweller", description: "", displayOrder: 480 },
    { sr: 49, typeCode: "Jewellery", typeName: "Jewellery", description: "", displayOrder: 500 },
    { sr: 50, typeCode: "JEWELRY", typeName: "JEWELRY", description: "", displayOrder: 510 },
    { sr: 51, typeCode: "Jewels29", typeName: "Jewels", description: "", displayOrder: 520 },
    { sr: 52, typeCode: "Kiaan", typeName: "Kiaan", description: "", displayOrder: 530 },
    { sr: 53, typeCode: "KRP JEWELLERY", typeName: "KRP JEWELLERY", description: "", displayOrder: 540 },
    { sr: 54, typeCode: "LGD JEWELLERY", typeName: "LGD JEWELLERY", description: "", displayOrder: 550 },
    { sr: 55, typeCode: "Luztre Jewellery", typeName: "Luztre Jewellery", description: "", displayOrder: 560 },
    { sr: 56, typeCode: "MALE", typeName: "MALE", description: "", displayOrder: 570 },
    { sr: 57, typeCode: "NA", typeName: "NA", description: "", displayOrder: 580 },
    { sr: 58, typeCode: "Nz", typeName: "Nazaria", description: "Nazaria", displayOrder: 590 },
    { sr: 59, typeCode: "Jewels", typeName: "Necklace", description: "GOLD", displayOrder: 600 },
    { sr: 60, typeCode: "NC", typeName: "Necklace1", description: "Women Necklace", displayOrder: 610 },
    { sr: 61, typeCode: "neckless", typeName: "neckless", description: "", displayOrder: 620 },
    { sr: 62, typeCode: "New Type", typeName: "New Type", description: "", displayOrder: 650 },
    { sr: 63, typeCode: "NOSE PIN Jewellery", typeName: "NOSE PIN Jewellery", description: "", displayOrder: 660 },
    { sr: 64, typeCode: "Rings", typeName: "Rings", description: "", displayOrder: 670 },
    { sr: 65, typeCode: "set", typeName: "set", description: "", displayOrder: 680 },
    { sr: 66, typeCode: "SILVER", typeName: "SILVER", description: "", displayOrder: 690 },
    { sr: 67, typeCode: "silver jewellery", typeName: "silver jewellery", description: "", displayOrder: 700 },
    { sr: 68, typeCode: "Sunglasses", typeName: "Sunglasses", description: "", displayOrder: 710 },
    { sr: 69, typeCode: "WOMEN JEWELLERY", typeName: "WOMEN JEWELLERY", description: "", displayOrder: 720 },
    { sr: 70, typeCode: "WOMEN RING", typeName: "WOMEN RING", description: "", displayOrder: 730 }
  ];
  export const genderMainData = [              
    { sr: 1, genderCode: "baby", genderName: "baby", description: "", displayOrder: 1 },
    { sr: 2, genderCode: "Her", genderName: "Her", description: "", displayOrder: 1 },
    { sr: 3, genderCode: "baba", genderName: "baba", description: "baba", displayOrder: 1 },
    { sr: 4, genderCode: "Gender", genderName: "Gender", description: "Gender", displayOrder: 1 },
    { sr: 5, genderCode: "Female", genderName: "Female", description: "", displayOrder: 2 },
    { sr: 6, genderCode: "Male", genderName: "Male", description: "", displayOrder: 3 },
    { sr: 7, genderCode: "KIDS", genderName: "KIDS", description: "", displayOrder: 5 },
    { sr: 8, genderCode: "MEN", genderName: "MEN", description: "", displayOrder: 6 },
    { sr: 9, genderCode: "WOMEN", genderName: "WOMEN", description: "", displayOrder: 7 },
    { sr: 10, genderCode: "G", genderName: "G", description: "", displayOrder: 8 },
    { sr: 11, genderCode: "M", genderName: "M", description: "", displayOrder: 9 },
    { sr: 12, genderCode: "4564", genderName: "4564", description: "bacelet", displayOrder: 9 },
    { sr: 13, genderCode: "Infrant", genderName: "Infrant", description: "", displayOrder: 10 },
    { sr: 14, genderCode: "girl", genderName: "girl", description: "", displayOrder: 10 },
    { sr: 15, genderCode: "NA", genderName: "NA", description: "", displayOrder: 11 },
    { sr: 16, genderCode: "None", genderName: "None", description: "", displayOrder: 12 },
    { sr: 17, genderCode: "His", genderName: "Men", description: "Sk", displayOrder: 12 },
    { sr: 18, genderCode: "p_male", genderName: "p_male", description: "", displayOrder: 12 },
    { sr: 19, genderCode: "LADIES", genderName: "LADIES", description: "", displayOrder: 13 },
    { sr: 20, genderCode: "GENTS", genderName: "GENTS", description: "", displayOrder: 14 }
  ];
  export const occasionMainData = [
    { sr: 1, occasionCode: "Anniversary", occasionName: "Anniversary", description: "", displayOrder: 1 },
    { sr: 2, occasionCode: "CH", occasionName: "CHRISTMAS", description: "25 DECEMBER", displayOrder: 1 },
    { sr: 3, occasionCode: "Occasion", occasionName: "Occasion", description: "Occasion", displayOrder: 1 },
    { sr: 4, occasionCode: "baba", occasionName: "baba", description: "baba", displayOrder: 2 },
    { sr: 5, occasionCode: "HI", occasionName: "HOLI", description: "", displayOrder: 2 },
    { sr: 6, occasionCode: "Engagement", occasionName: "Engagement", description: "", displayOrder: 2 },
    { sr: 7, occasionCode: "Wedding", occasionName: "Wedding", description: "", displayOrder: 3 },
    { sr: 8, occasionCode: "Office Wear", occasionName: "Office Wear", description: "", displayOrder: 5 },
    { sr: 9, occasionCode: "A", occasionName: "A", description: "", displayOrder: 6 },
    { sr: 10, occasionCode: "8966", occasionName: "Diwali", description: "22DN", displayOrder: 7 },
    { sr: 11, occasionCode: "DIWALI", occasionName: "DIWALI", description: "", displayOrder: 7 },
    { sr: 12, occasionCode: "Marrige", occasionName: "Marrige", description: "", displayOrder: 8 },
    { sr: 13, occasionCode: "NA", occasionName: "NA", description: "", displayOrder: 9 },
    { sr: 14, occasionCode: "0", occasionName: "0", description: "", displayOrder: 10 },
    { sr: 15, occasionCode: "DEFAULT", occasionName: "DEFAULT", description: "", displayOrder: 11 },
    { sr: 16, occasionCode: "Regular", occasionName: "Daily", description: "", displayOrder: 15 },
    { sr: 17, occasionCode: "nav", occasionName: "navratri", description: "navratri", displayOrder: 20 },
    { sr: 18, occasionCode: "Holi", occasionName: "Holi", description: "Sk", displayOrder: 20 },
    { sr: 19, occasionCode: "BIRTH DAY", occasionName: "BIRTH DAY", description: "", displayOrder: 21 },
    { sr: 20, occasionCode: "Party Wear", occasionName: "Party Wear", description: "", displayOrder: 22 }
  ];
  export const styleMainData = [
    { sr: 1, styleCode: "Casting", styleName: "Casting", description: "", displayOrder: 1 },
    { sr: 2, styleCode: "Style", styleName: "Style", description: "Style", displayOrder: 1 },
    { sr: 3, styleCode: "10.25", styleName: "10.25", description: "", displayOrder: 2 },
    { sr: 4, styleCode: "baba", styleName: "baba", description: "baba", displayOrder: 2 },
    { sr: 5, styleCode: "Flower", styleName: "Flower", description: "", displayOrder: 3 },
    { sr: 6, styleCode: "Round", styleName: "Round", description: "", displayOrder: 4 },
    { sr: 7, styleCode: "HANDMADE", styleName: "HANDMADE", description: "", displayOrder: 5 },
    { sr: 8, styleCode: "Casual", styleName: "Casual", description: "", displayOrder: 8 },
    { sr: 9, styleCode: "traditional", styleName: "traditional", description: "", displayOrder: 9 },
    { sr: 10, styleCode: "FANCY", styleName: "FANCY", description: "", displayOrder: 10 },
    { sr: 11, styleCode: "NA", styleName: "NA", description: "", displayOrder: 10 },
    { sr: 12, styleCode: "0", styleName: "0", description: "", displayOrder: 11 },
    { sr: 13, styleCode: "DEFAULT", styleName: "DEFAULT", description: "", displayOrder: 12 },
    { sr: 14, styleCode: "p_round", styleName: "p_round", description: "", displayOrder: 12 },
    { sr: 15, styleCode: "RN", styleName: "Round", description: "", displayOrder: 15 },
    { sr: 16, styleCode: "Band", styleName: "Band", description: "", displayOrder: 16 },
    { sr: 17, styleCode: "Engagement", styleName: "Engagement", description: "", displayOrder: 17 },
    { sr: 18, styleCode: "REGULAR56", styleName: "REGULAR", description: "", displayOrder: 18 },
    { sr: 19, styleCode: "Solitaire", styleName: "Solitaire", description: "", displayOrder: 19 },
    { sr: 20, styleCode: "Bridal Set", styleName: "Bridal Set", description: "", displayOrder: 20 }
  ];
  